app_management:
  install_apps:  # Включить/выключить установку приложений
    enabled: true  # true, если нужно устанавливать приложения
    install_packages:  # Список пакетов для установки
      - name: "World.IPTV"
        path: "apk/World.IPTV.apk"
        url: "https://github.com/Romaxa55/Smart-TV-Auto-Setup/releases/download/v1.0.0/World.IPTV.apk"
  remove_apps: false  # Включить удаление ненужных приложений
  remove_launchers:  # Включить/выключить удаление лаунчеров
    enabled: true  # true, если нужно удалять лаунчеры
    auto: true  # true, если нужно автоматически найти и удалить лаунчеры
    launchers_list:  # Список лаунчеров для удаления (если auto: false)
      - com.htc.htclauncherhighenglishd08
      - com.ktc.launcher
